networks:
  alecs:
    name: alecs_network

services:
  ############################
  # Postgres DB
  ############################
  alecontrollocircolari: # container name
    image: controllo-circolari
    env_file:
      - ./env-variables.properties
    networks:
      - alecs
    build:
      context: ./SpringBootApp
