networks:
  alecs:
    name: alecs_network

services:
  ############################
  # Postgres DB
  ############################
  springapp: # container name
    image: controllo-circolari
    env_file:
      - ./env-variables.properties
    networks:
      - alecs
    build:
      context: ./SpringBootApp
    ports:
      - "8080:8080"
