spring:
    application:
        name: controllocircolariscuola

logging:
  level:
    root: INFO
    reactor:
      Flux: OFF
    com:
      alecs: DEBUG

com:
  alecs:
    controllocircolariscuola:
      telegram:
        chat-id: -4500448339
        token: ${ALECS_TELEGRAM_BOT_TOKEN}